import Head from 'next/head'

export default function Home() {
  return (
    <div className="flex flex-col w-full h-full min-h-screen overflow-hidden bg-brand-light">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="min-w-full px-4 text-gray-800 py-14 md:px-0">
        <div className="container flex items-center justify-between h-full max-w-5xl mx-auto">
          {/* Logo */}
          {/* <Link href="#"> */}
          <a className="text-xl font-bold font-coiny md:text-3xl">
            <span className="pr-2 text-transparent bg-gradient-to-br from-brand-blue to-brand-purple bg-clip-text ">
              Bored
            </span>
            Ape
          </a>
          {/* </Link> */}
        </div>
      </header>

      <main className="bg-red-700">
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
